<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8c0e20e8-30c3-4fac-acc4-0ece2c86d735</elementGuidId>
    <imagePath></imagePath>
    <name>button_jewelery</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[2]/div[1]/button[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Jewelery')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Jewelery\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Jewelery</value>
        <webElementGuid>0f07320f-a967-406a-8732-271e70f681d1</webElementGuid>
    </webElementProperties>
</WebElementEntity>