<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>form_register</name>
   <tag></tag>
   <elementGuidId>d26baa16-e1f6-42a9-8774-b18eeb2dff84</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/form[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'Full Name
         Email address
         Password
         Confirm Password
         
         ...[truncated lines=8]')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Full Name
      Email address
      Password
      Confirm Password
      
      ...[truncated lines=8]</value>
      <webElementGuid>89cfb6ee-9abf-4b7e-9bf8-2a49451c1b51</webElementGuid>
   </webElementProperties>
</WebElementEntity>
