<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d448f078-1397-45d4-a954-3aab0e9f828c</elementGuidId>
    <imagePath></imagePath>
    <name>link_reactEcommerce</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'React Ecommerce')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"React Ecommerce\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>0f07320f-a967-406a-8732-271e70f681d1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>React Ecommerce</value>
        <webElementGuid>0f07320f-a967-406a-8732-271e70f681d1</webElementGuid>
    </webElementProperties>
</WebElementEntity>