<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9f3e6368-b5c9-4269-b808-863065a4f785</elementGuidId>
    <imagePath></imagePath>
    <name>link_reactEcommerce</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://ecom-react-clone.vercel.app/') and equals(@text,'React Ecommerce')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"React Ecommerce\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://ecom-react-clone.vercel.app/</value>
        <webElementGuid>025ee98e-a00a-4d01-8560-93b8bfeff023</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>React Ecommerce</value>
        <webElementGuid>025ee98e-a00a-4d01-8560-93b8bfeff023</webElementGuid>
    </webElementProperties>
</WebElementEntity>