<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f1b38b1b-b94c-432c-a841-f1f017221ca0</elementGuidId>
    <imagePath></imagePath>
    <name>link_home</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://ecom-react-clone.vercel.app/') and equals(@text,'Home')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Home\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://ecom-react-clone.vercel.app/</value>
        <webElementGuid>025ee98e-a00a-4d01-8560-93b8bfeff023</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Home</value>
        <webElementGuid>025ee98e-a00a-4d01-8560-93b8bfeff023</webElementGuid>
    </webElementProperties>
</WebElementEntity>