<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_goToCart</name>
   <tag></tag>
   <elementGuidId>6bc17b0a-c4aa-49fd-8d2c-2e2e017b57ff</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'btn btn-dark mx-3') and equals(@href,'/cart') and equals(@text,'Go to Cart')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="btn\ btn-dark\ mx-3"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:text=\"Go to Cart\"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-dark mx-3</value>
      <webElementGuid>89cfb6ee-9abf-4b7e-9bf8-2a49451c1b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart</value>
      <webElementGuid>89cfb6ee-9abf-4b7e-9bf8-2a49451c1b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go to Cart</value>
      <webElementGuid>89cfb6ee-9abf-4b7e-9bf8-2a49451c1b51</webElementGuid>
   </webElementProperties>
</WebElementEntity>
